name: CI/CD for Furniture Store

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # ✅ latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4 # ✅ latest version
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Build project
        run: npm run build

      - name: Upload production-ready files
        uses: actions/upload-artifact@v4   # ✅ upgraded to v4
        with:
          name: production-files
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # ✅ upgraded to v4
        with:
          name: production-files
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
